#=================================================================
# 对象存储配置
#=================================================================
storage:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: lishuwang
    secretKey: lishuwang
  aliyun-oss:
    endpoint: oss-cn-beijing.aliyuncs.com # 改成你自己的
    accessKey: LTAI5t6NFVzvk8usxzRho1nF # 改成你自己的
    secretKey: BUxuaC6y4C95aPu2MuedoOdx9lGyji # 改成你自己的
